/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudentRouteImport } from './routes/student'
import { Route as FacultyIndexRouteImport } from './routes/faculty.index'
import { Route as FacultyGenerateRouteImport } from './routes/faculty.generate'
import { Route as FacultyProfileRouteImport } from './routes/faculty.profile'
import { Route as FacultySettingsRouteImport } from './routes/faculty.settings'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentJoinRouteImport } from './routes/student.join'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentSettingsRouteImport } from './routes/student.settings'
import { Route as FacultyClassroomsIndexRouteImport } from './routes/faculty.classrooms.index'
import { Route as FacultyClassroomsIdRouteImport } from './routes/faculty.classrooms.$id'
import { Route as FacultyMaterialsIndexRouteImport } from './routes/faculty.materials.index'
import { Route as FacultyMaterialsIdRouteImport } from './routes/faculty.materials.$id'
import { Route as StudentMaterialsIndexRouteImport } from './routes/student.materials.index'
import { Route as StudentMaterialsIdRouteImport } from './routes/student.materials.$id'
import { Route as FacultyClassroomsIdSyllabusRouteImport } from './routes/faculty.classrooms.$id.syllabus'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyGenerateRoute = FacultyGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyProfileRoute = FacultyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultySettingsRoute = FacultySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FacultyRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentJoinRoute = StudentJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const FacultyClassroomsIndexRoute = FacultyClassroomsIndexRouteImport.update({
  id: '/classrooms/',
  path: '/classrooms/',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyClassroomsIdRoute = FacultyClassroomsIdRouteImport.update({
  id: '/classrooms/$id',
  path: '/classrooms/$id',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyMaterialsIndexRoute = FacultyMaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyMaterialsIdRoute = FacultyMaterialsIdRouteImport.update({
  id: '/materials/$id',
  path: '/materials/$id',
  getParentRoute: () => FacultyRoute,
} as any)
const StudentMaterialsIndexRoute = StudentMaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMaterialsIdRoute = StudentMaterialsIdRouteImport.update({
  id: '/materials/$id',
  path: '/materials/$id',
  getParentRoute: () => StudentRoute,
} as any)
const FacultyClassroomsIdSyllabusRoute =
  FacultyClassroomsIdSyllabusRouteImport.update({
    id: '/syllabus',
    path: '/syllabus',
    getParentRoute: () => FacultyClassroomsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/faculty/generate': typeof FacultyGenerateRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/faculty/settings': typeof FacultySettingsRoute
  '/student/join': typeof StudentJoinRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/settings': typeof StudentSettingsRoute
  '/faculty/': typeof FacultyIndexRoute
  '/student/': typeof StudentIndexRoute
  '/faculty/classrooms/$id': typeof FacultyClassroomsIdRouteWithChildren
  '/faculty/materials/$id': typeof FacultyMaterialsIdRoute
  '/student/materials/$id': typeof StudentMaterialsIdRoute
  '/faculty/classrooms/': typeof FacultyClassroomsIndexRoute
  '/faculty/materials/': typeof FacultyMaterialsIndexRoute
  '/student/materials/': typeof StudentMaterialsIndexRoute
  '/faculty/classrooms/$id/syllabus': typeof FacultyClassroomsIdSyllabusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/faculty/generate': typeof FacultyGenerateRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/faculty/settings': typeof FacultySettingsRoute
  '/student/join': typeof StudentJoinRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/settings': typeof StudentSettingsRoute
  '/faculty': typeof FacultyIndexRoute
  '/student': typeof StudentIndexRoute
  '/faculty/classrooms/$id': typeof FacultyClassroomsIdRouteWithChildren
  '/faculty/materials/$id': typeof FacultyMaterialsIdRoute
  '/student/materials/$id': typeof StudentMaterialsIdRoute
  '/faculty/classrooms': typeof FacultyClassroomsIndexRoute
  '/faculty/materials': typeof FacultyMaterialsIndexRoute
  '/student/materials': typeof StudentMaterialsIndexRoute
  '/faculty/classrooms/$id/syllabus': typeof FacultyClassroomsIdSyllabusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/faculty/generate': typeof FacultyGenerateRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/faculty/settings': typeof FacultySettingsRoute
  '/student/join': typeof StudentJoinRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/settings': typeof StudentSettingsRoute
  '/faculty/': typeof FacultyIndexRoute
  '/student/': typeof StudentIndexRoute
  '/faculty/classrooms/$id': typeof FacultyClassroomsIdRouteWithChildren
  '/faculty/materials/$id': typeof FacultyMaterialsIdRoute
  '/student/materials/$id': typeof StudentMaterialsIdRoute
  '/faculty/classrooms/': typeof FacultyClassroomsIndexRoute
  '/faculty/materials/': typeof FacultyMaterialsIndexRoute
  '/student/materials/': typeof StudentMaterialsIndexRoute
  '/faculty/classrooms/$id/syllabus': typeof FacultyClassroomsIdSyllabusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faculty'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/student'
    | '/faculty/generate'
    | '/faculty/profile'
    | '/faculty/settings'
    | '/student/join'
    | '/student/profile'
    | '/student/settings'
    | '/faculty/'
    | '/student/'
    | '/faculty/classrooms/$id'
    | '/faculty/materials/$id'
    | '/student/materials/$id'
    | '/faculty/classrooms/'
    | '/faculty/materials/'
    | '/student/materials/'
    | '/faculty/classrooms/$id/syllabus'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/faculty/generate'
    | '/faculty/profile'
    | '/faculty/settings'
    | '/student/join'
    | '/student/profile'
    | '/student/settings'
    | '/faculty'
    | '/student'
    | '/faculty/classrooms/$id'
    | '/faculty/materials/$id'
    | '/student/materials/$id'
    | '/faculty/classrooms'
    | '/faculty/materials'
    | '/student/materials'
    | '/faculty/classrooms/$id/syllabus'
  id:
    | '__root__'
    | '/'
    | '/faculty'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/student'
    | '/faculty/generate'
    | '/faculty/profile'
    | '/faculty/settings'
    | '/student/join'
    | '/student/profile'
    | '/student/settings'
    | '/faculty/'
    | '/student/'
    | '/faculty/classrooms/$id'
    | '/faculty/materials/$id'
    | '/student/materials/$id'
    | '/faculty/classrooms/'
    | '/faculty/materials/'
    | '/student/materials/'
    | '/faculty/classrooms/$id/syllabus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacultyRoute: typeof FacultyRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/generate': {
      id: '/faculty/generate'
      path: '/generate'
      fullPath: '/faculty/generate'
      preLoaderRoute: typeof FacultyGenerateRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/profile': {
      id: '/faculty/profile'
      path: '/profile'
      fullPath: '/faculty/profile'
      preLoaderRoute: typeof FacultyProfileRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/settings': {
      id: '/faculty/settings'
      path: '/settings'
      fullPath: '/faculty/settings'
      preLoaderRoute: typeof FacultySettingsRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/join': {
      id: '/student/join'
      path: '/join'
      fullPath: '/student/join'
      preLoaderRoute: typeof StudentJoinRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/faculty/classrooms/': {
      id: '/faculty/classrooms/'
      path: '/classrooms'
      fullPath: '/faculty/classrooms/'
      preLoaderRoute: typeof FacultyClassroomsIndexRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/classrooms/$id': {
      id: '/faculty/classrooms/$id'
      path: '/classrooms/$id'
      fullPath: '/faculty/classrooms/$id'
      preLoaderRoute: typeof FacultyClassroomsIdRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/materials/': {
      id: '/faculty/materials/'
      path: '/materials'
      fullPath: '/faculty/materials/'
      preLoaderRoute: typeof FacultyMaterialsIndexRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/materials/$id': {
      id: '/faculty/materials/$id'
      path: '/materials/$id'
      fullPath: '/faculty/materials/$id'
      preLoaderRoute: typeof FacultyMaterialsIdRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/student/materials/': {
      id: '/student/materials/'
      path: '/materials'
      fullPath: '/student/materials/'
      preLoaderRoute: typeof StudentMaterialsIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/materials/$id': {
      id: '/student/materials/$id'
      path: '/materials/$id'
      fullPath: '/student/materials/$id'
      preLoaderRoute: typeof StudentMaterialsIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/faculty/classrooms/$id/syllabus': {
      id: '/faculty/classrooms/$id/syllabus'
      path: '/syllabus'
      fullPath: '/faculty/classrooms/$id/syllabus'
      preLoaderRoute: typeof FacultyClassroomsIdSyllabusRouteImport
      parentRoute: typeof FacultyClassroomsIdRoute
    }
  }
}

interface FacultyClassroomsIdRouteChildren {
  FacultyClassroomsIdSyllabusRoute: typeof FacultyClassroomsIdSyllabusRoute
}

const FacultyClassroomsIdRouteChildren: FacultyClassroomsIdRouteChildren = {
  FacultyClassroomsIdSyllabusRoute: FacultyClassroomsIdSyllabusRoute,
}

const FacultyClassroomsIdRouteWithChildren =
  FacultyClassroomsIdRoute._addFileChildren(FacultyClassroomsIdRouteChildren)

interface FacultyRouteChildren {
  FacultyGenerateRoute: typeof FacultyGenerateRoute
  FacultyProfileRoute: typeof FacultyProfileRoute
  FacultySettingsRoute: typeof FacultySettingsRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
  FacultyClassroomsIdRoute: typeof FacultyClassroomsIdRouteWithChildren
  FacultyMaterialsIdRoute: typeof FacultyMaterialsIdRoute
  FacultyClassroomsIndexRoute: typeof FacultyClassroomsIndexRoute
  FacultyMaterialsIndexRoute: typeof FacultyMaterialsIndexRoute
}

const FacultyRouteChildren: FacultyRouteChildren = {
  FacultyGenerateRoute: FacultyGenerateRoute,
  FacultyProfileRoute: FacultyProfileRoute,
  FacultySettingsRoute: FacultySettingsRoute,
  FacultyIndexRoute: FacultyIndexRoute,
  FacultyClassroomsIdRoute: FacultyClassroomsIdRouteWithChildren,
  FacultyMaterialsIdRoute: FacultyMaterialsIdRoute,
  FacultyClassroomsIndexRoute: FacultyClassroomsIndexRoute,
  FacultyMaterialsIndexRoute: FacultyMaterialsIndexRoute,
}

const FacultyRouteWithChildren =
  FacultyRoute._addFileChildren(FacultyRouteChildren)

interface StudentRouteChildren {
  StudentJoinRoute: typeof StudentJoinRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentMaterialsIdRoute: typeof StudentMaterialsIdRoute
  StudentMaterialsIndexRoute: typeof StudentMaterialsIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentJoinRoute: StudentJoinRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentMaterialsIdRoute: StudentMaterialsIdRoute,
  StudentMaterialsIndexRoute: StudentMaterialsIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacultyRoute: FacultyRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
